"use client";

import { useState } from "react";
import { Check, Lock, ShieldCheck } from "lucide-react";
import { AuthFeatureShell, GlassCard, StatusPill } from "@/components/auth/AuthFeatureShell";

export default function AuthorizePage() {
  const [approved, setApproved] = useState(false);
  const scopes = ["Your basic profile", "Your MAX personalization preferences", "Your verified email address"];
  return <main className="min-h-screen bg-base px-4 py-10 text-ink sm:px-6"><div className="mx-auto max-w-xl"><div className="mb-6 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-white/10 bg-white/5"><ShieldCheck className="h-7 w-7 text-brand-300" /></div><p className="mt-4 text-xs font-semibold uppercase tracking-[.2em] text-brand-300">MAX Auth</p><h1 className="mt-2 font-display text-3xl font-semibold">Connect with MAX AI</h1><p className="mt-2 text-sm text-ink-muted">Review what this application can access before continuing.</p></div><AuthFeatureShell eyebrow="Authorization" title="Demo Application" description="This consent interface is ready for the production OAuth / PKCE flow. The final decision must always be enforced by the backend."><GlassCard><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-brand-500/10 text-brand-300"><Lock className="h-5 w-5" /></div><div><p className="font-medium">Requested access</p><p className="text-xs text-ink-muted">demo-client · max-ai.name.ng</p></div></div><div className="mt-5 space-y-2">{scopes.map((scope) => <div key={scope} className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[.025] p-3 text-sm"><Check className="h-4 w-4 text-success" />{scope}</div>)}</div><div className="mt-5 flex items-center gap-2"><StatusPill tone="warning">OAuth backend required</StatusPill><span className="text-xs text-ink-faint">No permission is granted by this preview.</span></div><div className="mt-6 grid grid-cols-2 gap-3"><button className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold hover:bg-white/10">Cancel</button><button onClick={() => setApproved(true)} className="rounded-xl bg-brand-500 px-4 py-3 text-sm font-semibold text-white hover:bg-brand-400">Allow access</button></div>{approved && <p className="mt-4 text-center text-sm text-success">Consent captured in the UI. Backend authorization is not yet enabled.</p>}</GlassCard></AuthFeatureShell></div></main>;
}
