"use client";
import { useState } from "react";
import { Download, Shield, RefreshCw, EyeOff } from "lucide-react";
import { AuthFeatureShell, GlassCard, FeatureRow, StatusPill } from "@/components/auth/AuthFeatureShell";

export default function PrivacyPage() {
 const [offline, setOffline] = useState(true); const [analytics, setAnalytics] = useState(false);
 return <AuthFeatureShell title="Privacy & data controls" description="Control how your MAX Account data is used across MAX products and future partner connections." eyebrow="Privacy"><div className="grid gap-5 md:grid-cols-2"><GlassCard><h2 className="font-display text-lg font-semibold">Your data</h2><div className="mt-3"><FeatureRow icon={<EyeOff className="h-5 w-5" />} title="Personalization data" description="Preferences are used to make MAX more useful to you." action={<StatusPill tone="success">Controlled</StatusPill>} /><FeatureRow icon={<Shield className="h-5 w-5" />} title="Partner permissions" description="Connected apps only receive scopes you approve." action={<StatusPill tone="success">Controlled</StatusPill>} /><FeatureRow icon={<Download className="h-5 w-5" />} title="Export your data" description="Prepare a portable copy of your MAX Account data." action={<button className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/5">Request</button>} /></div></GlassCard><GlassCard><h2 className="font-display text-lg font-semibold">Experience controls</h2><FeatureRow icon={<RefreshCw className="h-5 w-5" />} title="Offline profile cache" description="Keep a limited local copy so the account UI remains useful offline." action={<button onClick={() => setOffline(!offline)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${offline ? "bg-success/10 text-success" : "bg-white/10 text-ink-muted"}`}>{offline ? "On" : "Off"}</button>} /><FeatureRow icon={<EyeOff className="h-5 w-5" />} title="Optional analytics" description="Help improve MAX with non-essential product telemetry." action={<button onClick={() => setAnalytics(!analytics)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${analytics ? "bg-success/10 text-success" : "bg-white/10 text-ink-muted"}`}>{analytics ? "On" : "Off"}</button>} /></GlassCard></div><p className="mt-4 text-xs text-ink-faint">These controls are frontend preferences until corresponding backend persistence and consent enforcement is connected.</p></AuthFeatureShell>;
}
